---
# tasks file for ansible-r-win-domainjoin
- name: DNS Client
  win_dns_client:
    adapter_names: "{{ dns_client_adapter }}"
    ipv4_addresses: "{{ dns_client_dns_server_ip }}"
  when: dns_client_configure

- name: Join domain
  ansible.windows.win_domain_membership:
    dns_domain_name: "{{ domain_dns_name }}"
    domain_admin_user: "{{ domain_admin_user }}"
    domain_admin_password: "{{ domain_admin_password }}"
    domain_ou_path: "{{ domainjoin_ou_path }}"
    state: domain
  register: domain_state_ou
  when:
    - domain_join_oupath is defined
    - domain_join_oupath | length > 0

- name: Domain Member
  win_domain_membership:
    dns_domain_name: "{{ domain_dns_name }}"
    domain_admin_user: "{{ domain_admin_user }}"
    domain_admin_password: "{{ domain_admin_password }}"
    state: domain
  register: domain_state
  when:
    - (domain_join_oupath is undefined) or (domain_join_oupath | length == 0)

- name: Reboot when Domain Member requires it
  win_reboot:
  when:
    - (domain_join_oupath is undefined) or (domain_join_oupath | length == 0)    
    - domain_state.reboot_required

- name: Reboot (OU) when Domain Member requires it
  win_reboot:
  when: 
    - domain_join_oupath is defined
    - domain_join_oupath | length > 0
    - domain_state_ou.reboot_required